# Generated by Django 5.2.5 on 2025-08-09 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tone_of_communication', models.CharField(blank=True, max_length=100)),
                ('personality', models.CharField(blank=True, max_length=100)),
                ('greeting_open', models.CharField(blank=True, max_length=255)),
                ('business_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seller.businessprofile')),
            ],
        ),
    ]
