# Generated by Django 5.2.5 on 2025-08-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_chatbotsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatbotsettings',
            options={'verbose_name_plural': 'Chatbot settings'},
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='operating_hours',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
