# Generated by Django 5.2.5 on 2025-08-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_alter_chatbotsettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='audience_profile',
            field=models.TextField(blank=True, verbose_name='Ideal Customer Profile'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='target_market',
            field=models.CharField(blank=True, help_text='e.g., college students, young professionals', max_length=255),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='usp',
            field=models.TextField(blank=True, help_text='What makes your business special?', verbose_name='Unique Selling Proposition (USP)'),
        ),
    ]
