# Generated by Django 5.2.5 on 2025-08-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_businessprofile_audience_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='combo_packs',
            field=models.TextField(blank=True, help_text="Describe any special deals, e.g., 'Buy 2 T-shirts, get 1 free'", verbose_name='Special Combos or Packs'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='inventory_update_frequency',
            field=models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('OCCASIONALLY', 'Occasionally')], max_length=20, verbose_name='Inventory Update Frequency'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='product_categories',
            field=models.TextField(blank=True, help_text='Separate with commas, e.g., T-shirts, Jeans, Shoes', verbose_name='Main Product Categories'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='top_selling_products',
            field=models.TextField(blank=True, help_text='List a few examples for the AI to use.', verbose_name='Top-Selling Products or New Arrivals'),
        ),
    ]
