# Generated by Django 5.2.5 on 2025-08-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_businessprofile_combo_packs_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessprofile',
            options={'verbose_name_plural': 'Business profiles'},
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='accepts_card',
            field=models.BooleanField(default=False, verbose_name='Accept Credit/Debit Card'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='accepts_cod',
            field=models.BooleanField(default=False, verbose_name='Accept Cash on Delivery (COD)'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='accepts_upi',
            field=models.BooleanField(default=False, verbose_name='Accept UPI (PayTM, GPay, etc.)'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='delivery_methods',
            field=models.TextField(blank=True, help_text='e.g., Local hand-delivery, Courier service, In-store pickup', verbose_name='Delivery Methods You Offer'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='return_policy',
            field=models.TextField(blank=True, verbose_name='Your Return/Refund Policy'),
        ),
    ]
