# Generated by Django 5.2.5 on 2025-08-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_alter_businessprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='faqs',
            field=models.TextField(blank=True, help_text='List common questions and their answers. e.g., Q: Do you offer discounts? A: Yes, on orders above 2000.', verbose_name='Frequently Asked Questions (FAQs)'),
        ),
    ]
