# Generated by Django 5.2.5 on 2025-08-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_businessprofile_faqs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbotsettings',
            name='greeting_open',
        ),
        migrations.RemoveField(
            model_name='chatbotsettings',
            name='tone_of_communication',
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='ai_name',
            field=models.CharField(blank=True, help_text='Leave blank to use your business name.', max_length=100, verbose_name="AI Assistant's Name"),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='greeting',
            field=models.CharField(blank=True, max_length=255, verbose_name='Customer Greeting Message'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='phrases_to_avoid',
            field=models.TextField(blank=True, help_text='Separate phrases with a comma.', verbose_name='Phrases AI Should Avoid'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='product_description_tone',
            field=models.TextField(blank=True, verbose_name='Tone for Product Descriptions'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='signature_line',
            field=models.CharField(blank=True, help_text='e.g., Happy to help!', max_length=150, verbose_name='Signature Closing Line'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='use_emojis',
            field=models.BooleanField(default=True, verbose_name='Use Emojis in Conversation?'),
        ),
        migrations.AlterField(
            model_name='chatbotsettings',
            name='personality',
            field=models.TextField(blank=True, help_text='e.g., Friendly and casual, Formal and professional, Witty and humorous', verbose_name='AI Personality'),
        ),
    ]
