# Generated by Django 5.2.5 on 2025-08-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_remove_chatbotsettings_greeting_open_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotsettings',
            name='allow_negotiation',
            field=models.BooleanField(default=False, verbose_name='Allow AI to Negotiate on Price?'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='allow_upselling',
            field=models.BooleanField(default=False, verbose_name='Allow AI to Upsell (suggest related products)?'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='collect_address',
            field=models.BooleanField(default=True, verbose_name='Delivery Address'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='collect_email',
            field=models.BooleanField(default=False, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='collect_name',
            field=models.BooleanField(default=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='collect_phone',
            field=models.BooleanField(default=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='max_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='e.g., enter 10.00 for 10%', max_digits=5, verbose_name='Maximum Discount Percentage (%)'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='product_presentation',
            field=models.CharField(choices=[('TEXT_ONLY', 'Text description only'), ('IMAGE_FIRST', 'Image first, then text'), ('TEXT_WITH_PRICE', 'Text with price, then image')], default='TEXT_ONLY', max_length=20, verbose_name='How should the AI present products?'),
        ),
    ]
