# Generated by Django 5.2.5 on 2025-08-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0009_chatbotsettings_allow_negotiation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotsettings',
            name='custom_error_reply',
            field=models.CharField(blank=True, help_text="e.g., I'm not sure, but a team member will get back to you shortly.", max_length=255, verbose_name='Custom reply when confused'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='error_handling_strategy',
            field=models.CharField(choices=[('REPHRASE', 'Ask the customer to rephrase the question'), ('HANDOVER', 'Immediately say a human will take over')], default='HANDOVER', max_length=20, verbose_name="If the AI doesn't understand, what should it do?"),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='high_priority_alert',
            field=models.BooleanField(default=True, verbose_name='High-priority alert if a customer asks to call?'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='human_escalation_keywords',
            field=models.TextField(blank=True, help_text='List words that should immediately notify you (separate with commas). e.g., complaint, angry, legal', verbose_name='Keywords for Human Escalation'),
        ),
    ]
