# Generated by Django 5.2.5 on 2025-08-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0011_facebookpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='social_media_links',
            field=models.TextField(blank=True, help_text='Optional. Enter your social media links, one per line.', null=True),
        ),
    ]
