# Generated by Django 5.2.5 on 2025-09-01 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0013_socialconnection_delete_facebookpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(db_index=True, max_length=100)),
                ('customer_name', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('resolved', 'Resolved'), ('needs_attention', 'Needs Attention')], default='ongoing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='seller.socialconnection')),
            ],
            options={
                'unique_together': {('social_connection', 'customer_id')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('customer', 'Customer'), ('ai', 'AI'), ('seller', 'Seller')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='seller.conversation')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
